# Generated by Django 4.2.1 on 2023-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("AD", "Administrator"),
                    ("OW", "Owner"),
                    ("EM", "Employee"),
                    ("VI", "Visitor"),
                ],
                default="VI",
                max_length=2,
            ),
        ),
    ]
