# Generated by Django 4.2.1 on 2023-06-15 21:27

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    roles = [
        {"title": "Administrator", "description": "System owner"},
        {"title": "Owner", "description": "Club owner"},
        {"title": "Employee", "description": "Club employee"},
        {"title": "Visitor", "description": "Club visitor"},
    ]

    for role_name in roles:
        Role.objects.create(
            title=role_name["title"], description=role_name["description"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_role_profile_roles"),
    ]

    operations = [migrations.RunPython(create_roles)]
