(function(g){var window=this;'use strict';var yhb=function(a,b){a.Qa("onAutonavCoundownStarted",b)},k6=function(a,b,c){g.Bq(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Cg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.VN&&(b.lengthText?(e=b.lengthText||null,f=b.Kv||null):b.lengthSeconds&&(e=g.PR(b.lengthSeconds),f=g.PR(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.TN(d).type;var l=b instanceof g.VN?b.isLivePlayback:null,m=b instanceof g.VN?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,t=[],v=[];n&&t.push(n);p&&(t.push(p),v.push(p));q&&v.push(q);c={title:b.title,author:n,author_and_views:t.join(" \u2022 "),aria_label:b.ariaLabel||
g.XP('\u0414\u0438\u0432\u0438\u0442\u0438\u0441\u044f "$TITLE"',{TITLE:b.title}),duration:e,timestamp:f,url:b.Fk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:v.join(" \u2022 "),autoplayAlternativeHeader:b.Sr};b instanceof g.UN&&(c.playlist_length=b.playlistLength);a.update(c)},l6=function(a){var b=a.W(),c=b.C;
g.W.call(this,{G:"a",S:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:c?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{G:"div",La:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},X:[{G:"div",Y:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],xa:"{{duration}}"},{G:"div",La:["ytp-autonav-live-stamp"],xa:"\u0423 \u043f\u0440\u044f\u043c\u043e\u043c\u0443 \u0435\u0444\u0456\u0440\u0456"},
{G:"div",La:["ytp-autonav-upcoming-stamp"],xa:"\u041d\u0435\u0437\u0430\u0431\u0430\u0440\u043e\u043c"},{G:"div",S:"ytp-autonav-list-overlay",X:[{G:"div",S:"ytp-autonav-mix-text",xa:"\u041c\u0456\u043a\u0441"},{G:"div",S:"ytp-autonav-mix-icon"}]}]},{G:"div",La:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],xa:"{{title}}"},{G:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],xa:"{{author}}"},{G:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
xa:"{{views_and_publish_time}}"}]});this.I=a;this.suggestion=null;this.j=c;this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress)},m6=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{G:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.J=b;this.D=void 0;this.B=0;this.container=new g.W({G:"div",S:"ytp-autonav-endscreen-countdown-container"});g.E(this,this.container);this.container.Ha(this.element);b=a.W();var d=b.C;this.I=a;this.suggestion=null;this.onVideoDataChange("newdata",this.I.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.W({G:"div",S:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{G:"div",S:"ytp-autonav-endscreen-upnext-header"},{G:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",xa:"{{autoplayAlternativeHeader}}"},{G:"a",S:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:d?b.ea:""},X:[{G:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},X:[{G:"div",Y:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],
xa:"{{duration}}"},{G:"div",La:["ytp-autonav-live-stamp"],xa:"\u0423 \u043f\u0440\u044f\u043c\u043e\u043c\u0443 \u0435\u0444\u0456\u0440\u0456"},{G:"div",La:["ytp-autonav-upcoming-stamp"],xa:"\u041d\u0435\u0437\u0430\u0431\u0430\u0440\u043e\u043c"}]},{G:"div",S:"ytp-autonav-endscreen-video-info",X:[{G:"div",S:"ytp-autonav-endscreen-premium-badge"},{G:"div",S:"ytp-autonav-endscreen-upnext-title",xa:"{{title}}"},{G:"div",S:"ytp-autonav-endscreen-upnext-author",xa:"{{author}}"},{G:"div",S:"ytp-autonav-view-and-date",
xa:"{{views_and_publish_time}}"},{G:"div",S:"ytp-autonav-author-and-view",xa:"{{author_and_views}}"}]}]}]});g.E(this,this.j);this.j.Ha(this.container.element);d||this.T(this.j.Fa("ytp-autonav-endscreen-link-container"),"click",this.eR);this.I.vb(this.container.element,this,115127);this.I.vb(this.j.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({G:"div",S:"ytp-autonav-overlay"});g.E(this,this.overlay);this.overlay.Ha(this.container.element);this.u=new g.W({G:"div",S:"ytp-autonav-endscreen-button-container"});
g.E(this,this.u);this.u.Ha(this.container.element);this.cancelButton=new g.W({G:"button",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u0435 \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f"},xa:"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438"});
g.E(this,this.cancelButton);this.cancelButton.Ha(this.u.element);this.cancelButton.Ta("click",this.A_,this);this.I.vb(this.cancelButton.element,this,115129);this.playButton=new g.W({G:"a",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"\u0412\u0456\u0434\u0442\u0432\u043e\u0440\u0438\u0442\u0438 \u043d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e"},
xa:"\u0412\u0456\u0434\u0442\u0432\u043e\u0440\u0438\u0442\u0438"});g.E(this,this.playButton);this.playButton.Ha(this.u.element);this.playButton.Ta("click",this.eR,this);this.I.vb(this.playButton.element,this,115130);this.C=new g.pq(function(){zhb(c)},500);
g.E(this,this.C);this.dR();this.T(a,"autonavvisibility",this.dR);this.I.N("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.z_),this.T(a,"onAutonavCoundownStarted",this.Z5))},n6=function(a){var b=a.I.Ek(!0,a.I.isFullscreen());
g.Bq(a.container.element,"ytp-autonav-endscreen-small-mode",a.eh(b));g.Bq(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.zI);g.Bq(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.Gf());g.Bq(a.I.getRootNode(),"countdown-running",a.Kk());g.Bq(a.container.element,"ytp-player-content",a.I.Gf());g.sn(a.overlay.element,{width:b.width+"px"});if(!a.Kk()){a.I.Gf()?Ahb(a,Math.round(Bhb(a)/1E3)):Ahb(a);b=!!a.suggestion&&!!a.suggestion.Sr;var c=a.I.Gf()||!b;
g.Bq(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Bq(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.hR(a.u,a.I.Gf());g.Bq(a.element,"ytp-enable-w2w-color-transitions",Chb(a))}},zhb=function(a){var b=Bhb(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);Ahb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Kk()?a.select(!0):a.Kk()&&a.C.start()},Bhb=function(a){if(a.I.isFullscreen()){var b;
a=null==(b=a.I.getVideoData())?void 0:b.FQ;return-1===a||void 0===a?8E3:a}return 0<=a.I.As()?a.I.As():g.pL(a.I.W().experiments,"autoplay_time")||1E4},Chb=function(a){var b;
return!(null==(b=a.I.getVideoData())||!b.watchToWatchTransitionRenderer)},Ahb=function(a,b){b=void 0===b?-1:b;
a=a.j.Fa("ytp-autonav-endscreen-upnext-header");g.ef(a);if(0<=b){b=String(b);var c="\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e \u0447\u0435\u0440\u0435\u0437 $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e \u0447\u0435\u0440\u0435\u0437 $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.cf("\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(0,
d)));var e=g.bf("span");g.vq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.qf(e,b);a.appendChild(e);a.appendChild(g.cf("\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(d+c.length)));return}}g.qf(a,"\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435")},o6=function(a,b){g.W.call(this,{G:"div",
La:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},p6=function(a){g.W.call(this,{G:"div",
La:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},X:[{G:"div",S:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{G:"span",S:"ytp-upnext-top",X:[{G:"span",S:"ytp-upnext-header",xa:"\u0414\u0430\u043b\u0456"},{G:"span",S:"ytp-upnext-title",xa:"{{title}}"},{G:"span",S:"ytp-upnext-author",xa:"{{author}}"}]},{G:"a",S:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"\u0412\u0456\u0434\u0442\u0432\u043e\u0440\u0438\u0442\u0438 \u043d\u0430\u0441\u0442\u0443\u043f\u043d\u0435 \u0432\u0456\u0434\u0435\u043e"},
X:[{G:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},X:[{G:"circle",S:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",S:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",S:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",S:"ytp-upnext-bottom",
X:[{G:"span",S:"ytp-upnext-cancel"},{G:"span",S:"ytp-upnext-paused",xa:"\u0410\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u0435 \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f \u043f\u0440\u0438\u0437\u0443\u043f\u0438\u043d\u0435\u043d\u043e"}]}]});this.api=a;this.cancelButton=null;this.D=this.Fa("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.pq(this.sF,5E3,this);this.u=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=
new g.W({G:"button",La:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u0435 \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f"},xa:"\u0421\u043a\u0430\u0441\u0443\u0432\u0430\u0442\u0438"});g.E(this,this.cancelButton);this.cancelButton.Ta("click",this.B_,this);this.cancelButton.Ha(b);this.cancelButton&&this.api.vb(this.cancelButton.element,this,
115129);g.E(this,this.C);this.api.vb(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.C_);this.api.vb(b,this,115130);this.fR();this.T(a,"autonavvisibility",this.fR);this.T(a,"mdxnowautoplaying",this.I6);this.T(a,"mdxautoplaycanceled",this.J6);g.Bq(this.element,"ytp-upnext-mobile",this.api.W().u)},Dhb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.FQ;return-1===a||void 0===a?8E3:a}return 0<=a.api.As()?a.api.As():g.pL(a.api.W().experiments,"autoplay_time")||1E4},Ehb=function(a,b){b=Dhb(a,b);
var c=Math,d=c.min;var e=(0,g.IB)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Kk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Kk()&&a.j.start()},q6=function(a){o6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({G:"div",S:"ytp-suggestion-panel",X:[{G:"div",La:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],xa:"\u0406\u043d\u0448\u0456 \u0432\u0456\u0434\u0435\u043e"}]});this.K=new g.W({G:"div",S:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new m6(this.player);g.E(this,this.u);this.u.Ha(this.element);a.getVideoData().Qe?this.j=this.u:(this.j=new p6(a),g.eT(this.player,this.j.element,4),g.E(this,
this.j));this.overlay=new g.W({G:"div",S:"ytp-autonav-overlay-cancelled-state"});g.E(this,this.overlay);this.overlay.Ha(this.element);this.C=new g.iK(this);g.E(this,this.C);g.E(this,this.table);this.table.Ha(this.element);this.table.show();g.E(this,this.K);this.K.Ha(this.table.element);this.hide()},r6=function(a){var b=a.Gf();
b!==a.D&&(a.D=b,a.player.oa("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},s6=function(a,b){g.W.call(this,{G:"button",
La:["ytp-watch-on-youtube-button","ytp-button"],xa:"{{content}}"});this.I=a;this.buttonType=this.buttonType=b;b=this.I.getVideoData();if(a.N("embeds_enable_server_driven_watch_again_on_youtube")){var c,d;if(c=(a=null==(c=b.Ad)?void 0:null==(d=c.playerOverlays)?void 0:d.playerOverlayRenderer)&&g.Q(a.watchOnYoutubeButton,g.HKa))this.j=c}if(this.j)this.update({content:this.j.title}),this.I.Rf(this.element,this),this.I.ag(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:c=
"\u0414\u0438\u0432\u0438\u0442\u0438\u0441\u044f \u0437\u043d\u043e\u0432\u0443 \u043d\u0430 YouTube";d=156915;break;case 2:c="\u041f\u0440\u043e\u0434\u043e\u0432\u0436\u0438\u0442\u0438 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434 \u043d\u0430 YouTube";d=156942;break;default:c="\u041f\u0440\u043e\u0434\u043e\u0432\u0436\u0438\u0442\u0438 \u043f\u0435\u0440\u0435\u0433\u043b\u044f\u0434 \u043d\u0430 YouTube",d=156942}this.update({content:c});this.I.vb(this.element,this,d)}2===this.buttonType&&
g.xq(this.element,"ytp-continue-watching-button");this.Ta("click",this.onClick);g.hR(this,!0)},t6=function(a,b){o6.call(this,a,"embeds-lite-endscreen");
this.I=a;this.j=b;this.I.vb(this.element,this,156943);this.watchButton=new s6(a,2);g.E(this,this.watchButton);this.watchButton.Ha(this.element);this.hide()},Fhb=function(a){o6.call(this,a,"subscribecard-endscreen");
this.j=new g.W({G:"div",S:"ytp-subscribe-card",X:[{G:"img",S:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{G:"div",S:"ytp-subscribe-card-right",X:[{G:"div",S:"ytp-author-name",xa:"{{author}}"},{G:"div",S:"html5-subscribe-button-container"}]}]});g.E(this,this.j);this.j.Ha(this.element);var b=a.getVideoData();this.subscribeButton=new g.OU("\u041f\u0456\u0434\u043f\u0438\u0441\u0430\u0442\u0438\u0441\u044f",null,"\u0412\u0456\u0434\u043f\u0438\u0441\u0430\u0442\u0438\u0441\u044f",null,!0,!1,b.hk,
b.subscribed,"trailer-endscreen",null,a);g.E(this,this.subscribeButton);this.subscribeButton.Ha(this.j.Fa("html5-subscribe-button-container"));this.T(a,"videodatachange",this.Sa);this.Sa();this.hide()},u6=function(a){var b=a.W(),c=g.lK||g.qM?{style:"will-change: opacity"}:void 0,d=b.C,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",La:e,Y:{href:"{{url}}",target:d?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},X:[{G:"div",S:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{G:"span",S:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},X:[{G:"span",S:"ytp-videowall-still-info-bg",X:[{G:"span",S:"ytp-videowall-still-info-content",Y:c,X:[{G:"span",S:"ytp-videowall-still-info-title",xa:"{{title}}"},
{G:"span",S:"ytp-videowall-still-info-author",xa:"{{author_and_views}}"},{G:"span",S:"ytp-videowall-still-info-live",xa:"\u0423 \u043f\u0440\u044f\u043c\u043e\u043c\u0443 \u0435\u0444\u0456\u0440\u0456"},{G:"span",S:"ytp-videowall-still-info-duration",xa:"{{duration}}"}]}]}]},{G:"span",La:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{G:"span",S:"ytp-videowall-still-listlabel-icon"},"\u0421\u043f\u0438\u0441\u043e\u043a \u0432\u0456\u0434\u0442\u0432\u043e\u0440\u0435\u043d\u043d\u044f",
{G:"span",S:"ytp-videowall-still-listlabel-length",X:[" (",{G:"span",xa:"{{playlist_length}}"},")"]}]},{G:"span",La:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{G:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0456\u043a\u0441",{G:"span",S:"ytp-videowall-still-listlabel-length",xa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.iK(this);g.E(this,this.j);this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress);
this.j.T(a,"videodatachange",this.onVideoDataChange);a.Rf(this.element,this);this.onVideoDataChange()},v6=function(a){o6.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.V=null;this.u=new g.iK(this);g.E(this,this.u);this.J=new g.pq(function(){g.xq(b.element,"ytp-show-tiles")},0);
g.E(this,this.J);var c=new g.W({G:"button",La:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},X:[g.lR()]});g.E(this,c);c.Ha(this.element);c.Ta("click",this.G_,this);this.table=new g.eR({G:"div",S:"ytp-endscreen-content"});g.E(this,this.table);this.table.Ha(this.element);c=new g.W({G:"button",La:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"\u0414\u0430\u043b\u0456"},X:[g.mR()]});g.E(this,c);c.Ha(this.element);c.Ta("click",this.F_,this);a.getVideoData().Qe?
this.j=new m6(a,!0):this.j=new p6(a);g.E(this,this.j);g.eT(this.player,this.j.element,4);a.vb(this.element,this,158789);this.hide()},w6=function(a){return g.fT(a.player)&&a.dB()&&!a.C},x6=function(a){var b=a.Gf();
b!==a.K&&(a.K=b,a.player.oa("autonavvisibility"))},y6=function(a){o6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new s6(a,1);g.E(this,this.watchButton);this.watchButton.Ha(this.element);g.X8a(a)&&(this.j=new g.g3(a,g.OS(a)),g.E(this,this.j),this.u=new g.W({G:"div",La:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},X:[this.j]}),g.E(this,this.u),this.j.Ha(this.u.element),this.u.Ha(this.element));a.vb(this.element,this,156914);this.hide()},Jhb=function(a){g.fU.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.iK(this);g.E(this,this.listeners);var c=a.W(),d=a.getVideoData();d=d&&0!==d.endSeconds;g.nA(g.JM(c))&&d&&!g.aT(a)?(this.u=!0,this.endScreen=new t6(a,g.OS(a))):g.bT(a)?this.endScreen=new y6(a):Ghb(a)?(this.C=!0,Hhb(this),this.j?this.endScreen=new q6(a):this.endScreen=new v6(a)):c.yh?this.endScreen=new Fhb(a):this.endScreen=new o6(a);g.E(this,this.endScreen);g.eT(a,this.endScreen.element,4);Ihb(this);this.listeners.T(a,
"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.aG("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.bG("endscreen"),function(e){b.onCueRangeExit(e)})},Hhb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.yl&&a.B===b.Qe)return!1;a.j=b.yl;a.B=b.Qe;return!0},Ghb=function(a){a=a.W();
return a.Kd&&!a.yh},Ihb=function(a){a.player.Ne("endscreen");
var b=a.player.getVideoData();b=new g.ZF(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.ZF(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.cf([b,c])};
g.DW.prototype.Uz=g.ca(36,function(a){this.GO!==a&&(this.GO=a,this.vl())});
g.rV.prototype.gr=g.ca(35,function(a){this.u!==a&&(this.u=a,this.Sa())});
g.DW.prototype.gr=g.ca(34,function(a){this.shareButton&&this.shareButton.gr(a)});
g.nV.prototype.er=g.ca(33,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.DW.prototype.er=g.ca(32,function(a){this.overflowButton&&this.overflowButton.er(a)});
g.FU.prototype.bE=g.ca(31,function(a){this.HO!==a&&(this.HO=a,this.Dp())});
g.XS.prototype.As=g.ca(5,function(){return this.app.As()});
g.q_.prototype.As=g.ca(4,function(){return this.getVideoData().sS});g.x(l6,g.W);l6.prototype.select=function(){this.I.Wn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.xB||void 0)&&this.I.tb(this.element)};
l6.prototype.onClick=function(a){g.uT(a,this.I,this.j,this.suggestion.sessionData||void 0)&&this.select()};
l6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.eQ(a)||(this.select(),g.fQ(a))}};g.x(m6,g.W);g.k=m6.prototype;g.k.KE=function(a){this.suggestion!==a&&(this.suggestion=a,k6(this.j,a),this.playButton.updateValue("url",this.suggestion.Fk()),n6(this))};
g.k.Kk=function(){return 0<this.B};
g.k.cA=function(){this.Kk()||(this.B=Date.now(),zhb(this),yhb(this.I,Bhb(this)),g.Bq(this.I.getRootNode(),"countdown-running",this.Kk()))};
g.k.cw=function(){this.wr();zhb(this);var a=this.j.Fa("ytp-autonav-endscreen-upnext-header");a&&g.qf(a,"\u041d\u0430\u0441\u0442\u0443\u043f\u043d\u0435")};
g.k.wr=function(){this.Kk()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.wr()};
g.k.eR=function(a){g.uT(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.tb(this.playButton.element):a.currentTarget===this.j.Fa("ytp-autonav-endscreen-link-container")&&(a=this.j.Fa("ytp-autonav-endscreen-link-container"),this.I.Za(a,!0),this.I.tb(a)),this.select())};
g.k.A_=function(){this.I.tb(this.cancelButton.element);g.ZS(this.I,!0);this.D&&this.I.Qa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.L1)?void 0:c.command};
g.k.Z5=function(a){if(Chb(this)){var b=this.I.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.WR(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.WR(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.WR(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.WR(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.WR(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.WR(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Bq(this.element,"ytp-w2w-animate",!0)}};
g.k.z_=function(a){this.I.N("web_autonav_color_transition")&&2!==a&&g.Bq(this.element,"ytp-w2w-animate",!1)};
g.k.dR=function(){var a=this.I.Gf();this.J&&this.Cb!==a&&g.hR(this,a);n6(this);this.I.Za(this.container.element,a);this.I.Za(this.cancelButton.element,a);this.I.Za(this.j.Fa("ytp-autonav-endscreen-link-container"),a);this.I.Za(this.playButton.element,a)};
g.k.eh=function(a){return 400>a.width||459>a.height};g.x(o6,g.W);g.k=o6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.dB=function(){return!1};
g.k.Gf=function(){return!1};
g.k.BV=function(){return!1};g.x(p6,g.W);g.k=p6.prototype;g.k.sF=function(){this.notification&&(this.C.stop(),this.Hc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.KE=function(a){this.suggestion=a;k6(this,a,"hqdefault.jpg")};
g.k.fR=function(){g.hR(this,this.api.Gf());this.api.Za(this.element,this.api.Gf());this.api.Za(this.Fa("ytp-upnext-autoplay-icon"),this.api.Gf());this.cancelButton&&this.api.Za(this.cancelButton.element,this.api.Gf())};
g.k.R6=function(){window.focus();this.sF()};
g.k.cA=function(a){var b=this;this.Kk()||(g.lD("a11y-announce","\u0414\u0430\u043b\u0456 "+this.suggestion.title),this.u=(0,g.IB)(),this.j=new g.pq(function(){Ehb(b,a)},25),Ehb(this,a),yhb(this.api,Dhb(this,a)));
g.zq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.Kk=function(){return!!this.j};
g.k.cw=function(){this.wr();this.u=(0,g.IB)();Ehb(this);g.xq(this.element,"ytp-upnext-autoplay-paused")};
g.k.wr=function(){this.Kk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.W().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.sF(),this.notification=new Notification("\u0414\u0430\u043b\u0456",{body:this.suggestion.title,icon:this.suggestion.Cg()}),this.B=this.T(this.notification,"click",this.R6),this.C.start())}this.wr();this.api.nextVideo(!1,a)};
g.k.C_=function(a){!g.pf(this.cancelButton.element,g.dQ(a))&&g.uT(a,this.api)&&(this.api.Gf()&&this.api.tb(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.B_=function(){this.api.Gf()&&this.cancelButton&&this.api.tb(this.cancelButton.element);g.ZS(this.api,!0)};
g.k.I6=function(a){this.api.getPresentingPlayerType();this.show();this.cA(a)};
g.k.J6=function(){this.api.getPresentingPlayerType();this.wr();this.hide()};
g.k.va=function(){this.wr();this.sF();g.W.prototype.va.call(this)};g.x(q6,o6);g.k=q6.prototype;g.k.create=function(){o6.prototype.create.call(this);this.C.T(this.player,"appresize",this.GA);this.C.T(this.player,"onVideoAreaChange",this.GA);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.gR);this.C.T(this.player,"autonavcancel",this.D_);this.onVideoDataChange()};
g.k.show=function(){o6.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.ZS(this.player,!1);g.fT(this.player)&&this.dB()&&!this.B?(r6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.cA():3===this.videoData.autonavState&&this.j.cw()):(g.ZS(this.player,!0),r6(this));this.GA()};
g.k.hide=function(){o6.prototype.hide.call(this);this.j.cw();r6(this)};
g.k.GA=function(){var a=this.player.Ek(!0,this.player.isFullscreen());r6(this);n6(this.u);g.Bq(this.element,"ytp-autonav-cancelled-small-mode",this.eh(a));g.Bq(this.element,"ytp-autonav-cancelled-tiny-mode",this.HG(a));g.Bq(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.sn(this.overlay.element,{width:a.width+"px"});if(!this.D)for(a=0;a<this.videos.length;a++)g.Bq(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.N("web_player_autonav_empty_suggestions_fix")){var b=g.BO(this.videoData);b&&(this.j.KE(b),this.j!==this.u&&this.u.KE(b))}if(a&&a.length)for(b=0;b<Khb.length;++b){var c=Khb[b];if(a&&a[c]){this.videos[b]=new l6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,k6(d,c));g.E(this,this.videos[b]);this.videos[b].Ha(this.K.element)}}this.GA()}};
g.k.gR=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.j.wr(),this.Cb&&this.GA()):(this.J=!0,this.Gf()&&(2===a?this.j.cA():3===a&&this.j.cw()))};
g.k.D_=function(a){a?this.gR(1):(this.B=null,this.J=!1)};
g.k.dB=function(){return 1!==this.videoData.autonavState};
g.k.eh=function(a){return(910>a.width||459>a.height)&&!this.HG(a)&&!(400>=a.width||360>=a.height)};
g.k.HG=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Gf=function(){return this.Cb&&g.fT(this.player)&&this.dB()&&!this.B};
var Khb=[1,3,2,4];g.x(s6,g.W);g.k=s6.prototype;g.k.onClick=function(a){this.I.N("web_player_log_click_before_generating_ve_conversion_params")&&this.I.tb(this.element);this.j?this.I.Qa("innertubeCommand",g.Q(this.j.onTap,g.bR)):g.vT(this.getVideoUrl(),this.I,a);this.I.N("web_player_log_click_before_generating_ve_conversion_params")||this.I.tb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.I.getVideoUrl(a,!1,!1,!0);var b=this.I.W();if(g.sM(b)||g.BM(b)){var c={};b.Ca&&g.sM(b)&&g.FS(c,b.loaderUrl);g.sM(b)&&g.MS(this.I,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.ES(c,b);a=g.Ij(a,c)}return a};
g.k.Za=function(){this.I.Za(this.element,this.Cb&&this.ea)};
g.k.show=function(){g.W.prototype.show.call(this);this.Za()};
g.k.hide=function(){g.W.prototype.hide.call(this);this.Za()};
g.k.kc=function(a){g.W.prototype.kc.call(this,a);this.Za()};g.x(t6,o6);t6.prototype.show=function(){3!==this.player.getPlayerState()&&(o6.prototype.show.call(this),this.j.Uz(!0),this.j.gr(!0),this.I.W().Ic||this.j.er(!0),this.I.Za(this.element,!0),this.watchButton.kc(!0))};
t6.prototype.hide=function(){o6.prototype.hide.call(this);this.j.Uz(!1);this.j.gr(!1);this.j.er(!1);this.I.Za(this.element,!1);this.watchButton.kc(!1)};g.x(Fhb,o6);Fhb.prototype.Sa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.hk;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.x(u6,g.W);u6.prototype.select=function(){this.api.Wn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.xB||void 0)&&this.api.tb(this.element)};
u6.prototype.onClick=function(a){if(g.sM(this.api.W())&&this.api.N("web_player_log_click_before_generating_ve_conversion_params")){this.api.tb(this.element);var b=this.suggestion.Fk(),c={};g.gKa(this.api,c,"emb_rel_end");b=g.Ij(b,c);g.vT(b,this.api,a)}else g.uT(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
u6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.eQ(a)||(this.select(),g.fQ(a))}};
u6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.W();this.u=a.Cd?!1:b.C};g.x(v6,o6);g.k=v6.prototype;g.k.create=function(){o6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Lp();this.u.T(this.player,"appresize",this.Lp);this.u.T(this.player,"onVideoAreaChange",this.Lp);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.yJ);this.u.T(this.player,"autonavcancel",this.E_);a=this.videoData.autonavState;a!==this.V&&this.yJ(a);this.u.T(this.element,"transitionend",this.e8)};
g.k.destroy=function(){g.JA(this.u);g.rb(this.stills);this.stills=[];o6.prototype.destroy.call(this);g.zq(this.element,"ytp-show-tiles");this.J.stop();this.V=this.videoData.autonavState};
g.k.dB=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Cb;o6.prototype.show.call(this);g.zq(this.element,"ytp-show-tiles");this.player.W().u?g.rq(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.ZS(this.player,!1);w6(this)?(x6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.cA():3===this.videoData.autonavState&&this.j.cw()):(g.ZS(this.player,!0),x6(this));a!==this.Cb&&this.player.Za(this.element,!0)};
g.k.hide=function(){var a=this.Cb;o6.prototype.hide.call(this);this.j.cw();x6(this);a!==this.Cb&&this.player.Za(this.element,!1)};
g.k.e8=function(a){g.dQ(a)===this.element&&this.Lp()};
g.k.Lp=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.BO(d)];if(e.length){g.xq(this.element,"ytp-endscreen-paginate");var f=this.I.Ek(!0,this.I.isFullscreen());if(a=g.OS(this.I))a=a.Eg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,t=b/2,v=a<=l-2&&p>=t*n,y=b<=m-2&&p>=q*n;if((q+1)/t*d/h>h/(q/(t+1)*d)&&y)p-=q*n,b+=2;else if(v)p-=t*n,a+=2;else if(y)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Cn(f,n,p);g.sn(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.KE(g.BO(this.videoData));this.j instanceof
m6&&n6(this.j);g.Bq(this.element,"ytp-endscreen-takeover",w6(this));x6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,v=0,d&&l>=a-2&&m>=b-2?v=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(v=2):v=2),q=g.te(q+this.B,c),0!==v){t=this.stills[h];t||(t=new u6(this.player),this.stills[h]=t,f.appendChild(t.element));y=Math.floor(p*m/b);var A=Math.floor(n*l/a),G=Math.floor(p*(m+v)/b)-y-4,N=Math.floor(n*(l+v)/a)-A-4;g.yn(t.element,A,y);g.Cn(t.element,N,G);g.sn(t.element,"transitionDelay",
(m+l)/20+"s");g.Bq(t.element,"ytp-videowall-still-mini",1===v);g.Bq(t.element,"ytp-videowall-still-large",2<v);v=Math.max(N,G);g.Bq(t.element,"ytp-videowall-still-round-large",256<=v);g.Bq(t.element,"ytp-videowall-still-round-medium",96<v&&256>v);g.Bq(t.element,"ytp-videowall-still-round-small",96>=v);q=e[q];t.suggestion!==q&&(t.suggestion=q,v=t.api.W(),y=g.wq(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",k6(t,q,y),g.sM(v)&&!t.api.N("web_player_log_click_before_generating_ve_conversion_params")&&
(y=q.Fk(),A={},v.Ca&&g.FS(A,v.loaderUrl),g.MS(t.api,"addEmbedsConversionTrackingParams",[A]),y=g.Ij(y,g.ES(A,"emb_rel_end")),t.updateValue("url",y)),(q=(q=q.sessionData)&&q.itct)&&t.api.ag(t.element,q));h++}f.ariaBusy="false";g.Bq(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.nf(a.element),g.qb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Lp())};
g.k.F_=function(){this.B+=this.stills.length;this.Lp()};
g.k.G_=function(){this.B-=this.stills.length;this.Lp()};
g.k.BV=function(){return this.j.Kk()};
g.k.yJ=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.wr(),this.Cb&&this.Lp()):(this.D=!0,this.Cb&&w6(this)&&(2===a?this.j.cA():3===a&&this.j.cw()))};
g.k.E_=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.Za(this.stills[a].element,!0);this.yJ(1)}else this.C=null,this.D=!1;this.Lp()};
g.k.Gf=function(){return this.Cb&&w6(this)};g.x(y6,o6);y6.prototype.show=function(){if(3!==this.player.getPlayerState()){o6.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.Bq(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.OS(this.player))||c.bE(!0);this.player.Za(this.element,!0);this.watchButton.kc(!0)}};
y6.prototype.hide=function(){o6.prototype.hide.call(this);var a;null==(a=g.OS(this.player))||a.bE(!1);this.player.Za(this.element,!1);this.watchButton.kc(!1)};g.x(Jhb,g.fU);g.k=Jhb.prototype;g.k.zw=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.bT(this.player)||this.u)&&!b)return!0;var c;var d=!!((null==a?0:g.BO(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Ghb(this.player)||d;a=a.jj||g.BM(a.Ia);c=this.player.JB();return d&&!a&&!c&&!b};
g.k.Gf=function(){return this.endScreen.Gf()};
g.k.M4=function(){return this.Gf()?this.endScreen.BV():!1};
g.k.va=function(){this.player.Ne("endscreen");g.fU.prototype.va.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Bb().sf.get("heartbeat"),d=g.BO(a);!d||b.videoId!==d.videoId||a.JY?(this.player.Wn(b.videoId,void 0,void 0,!0,!0,b),c&&c.PG("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.fU.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.fU.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.zw()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Ihb(this);this.C&&Hhb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new q6(this.player):this.endScreen=new v6(this.player),g.E(this,this.endScreen),g.eT(this.player,this.endScreen.element,4))};g.eU("endscreen",Jhb);})(_yt_player);
