# Generated by Django 4.2.1 on 2023-06-27 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("13-14", "13.00-14.00"),
                            ("14-15", "14.00-15.00"),
                            ("15-16", "15.00-16.00"),
                            ("16-17", "16.00-17.00"),
                            ("17-18", "17.00-18.00"),
                            ("18-19", "18.00-19.00"),
                            ("19-20", "19.00-20.00"),
                            ("20-21", "20.00-21.00"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("AL", "Actual"), ("OD", "Outdated")],
                        default="AL",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("comment", models.CharField(max_length=128, null=True)),
                ("time", models.ManyToManyField(to="vr_club_site.bookingtime")),
            ],
        ),
    ]
