# Generated by Django 4.2.1 on 2023-07-28 09:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("vr_club_site", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="vrclub@gmail.com", max_length=64),
        ),
        migrations.AddField(
            model_name="booking",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(default="vrclub", max_length=32),
        ),
        migrations.AddField(
            model_name="booking",
            name="number_of_people",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="+380000000000",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="booking",
            name="comment",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="bookingtime",
            name="time",
            field=models.CharField(
                choices=[
                    ("12-13", "12.00-13.00"),
                    ("13-14", "13.00-14.00"),
                    ("14-15", "14.00-15.00"),
                    ("15-16", "15.00-16.00"),
                    ("16-17", "16.00-17.00"),
                    ("17-18", "17.00-18.00"),
                    ("18-19", "18.00-19.00"),
                    ("19-20", "19.00-20.00"),
                    ("20-21", "20.00-21.00"),
                    ("21-22", "21.00-22.00"),
                ],
                max_length=5,
            ),
        ),
    ]
