# Generated by Django 4.2.1 on 2023-07-29 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vr_club_site", "0002_remove_booking_user_booking_email_booking_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingtime",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
