# Generated by Django 3.2 on 2023-08-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_club_site', '0004_sessionseats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_people',
            new_name='people_count',
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, default='+380000000000', max_length=20, null=True),
        ),
    ]
