# Generated by Django 4.2.1 on 2023-07-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Games",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=256)),
                ("players", models.CharField(max_length=8)),
                ("age_category", models.CharField(max_length=4)),
                ("video_link", models.URLField()),
                ("image", models.ImageField(upload_to="games/")),
                (
                    "game_mode",
                    models.CharField(
                        choices=[
                            ("single", "Single Player"),
                            ("multiplayer", "Multiplayer"),
                            ("both", "Both (Single & Multiplayer)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("genre", models.ManyToManyField(to="games.genres")),
            ],
        ),
    ]
