# Generated by Django 4.2.1 on 2023-06-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortener",
            name="long_url",
            field=models.URLField(),
        ),
    ]
